name: AutoBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.x
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run generator
        working-directory: ./generator
        run: python3 gen.py
      - name: LaTeX compilation #1
        uses: dante-ev/latex-action@2021-A
        with: 
          root_file: template.tex
          working_directory: ./generator
          compiler: xelatex
      - name: LaTeX compilation #2
        uses: dante-ev/latex-action@2021-A
        with: 
          root_file: template.tex
          working_directory: ./generator
          compiler: xelatex
      - name: Move PDF to root and commit
        run: |
          cp generator/template.tex template.tex
          git config --local user.email "megaowier[bot]@gmail.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Auto Build" -a
      - name: Git Push
        uses: ad-m/github-push-action@v0.6.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
